/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-07-22 21:53:01 UTC)
 * on 2014-09-17 at 22:28:50 UTC 
 * Modify at your own risk.
 */

package epusp.pcs.os.model.person.victimendpoint;

/**
 * Service definition for Victimendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link VictimendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Victimendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.18.0-rc of the victimendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://epusp-pcsos.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "victimendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Victimendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Victimendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getVictim".
   *
   * This request holds the parameters needed by the victimendpoint server.  After setting any
   * optional parameters, call the {@link GetVictim#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public GetVictim getVictim(java.lang.Long id) throws java.io.IOException {
    GetVictim result = new GetVictim(id);
    initialize(result);
    return result;
  }

  public class GetVictim extends VictimendpointRequest<epusp.pcs.os.model.person.victimendpoint.model.Victim> {

    private static final String REST_PATH = "victim/{id}";

    /**
     * Create a request for the method "getVictim".
     *
     * This request holds the parameters needed by the the victimendpoint server.  After setting any
     * optional parameters, call the {@link GetVictim#execute()} method to invoke the remote
     * operation. <p> {@link
     * GetVictim#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetVictim(java.lang.Long id) {
      super(Victimendpoint.this, "GET", REST_PATH, null, epusp.pcs.os.model.person.victimendpoint.model.Victim.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetVictim setAlt(java.lang.String alt) {
      return (GetVictim) super.setAlt(alt);
    }

    @Override
    public GetVictim setFields(java.lang.String fields) {
      return (GetVictim) super.setFields(fields);
    }

    @Override
    public GetVictim setKey(java.lang.String key) {
      return (GetVictim) super.setKey(key);
    }

    @Override
    public GetVictim setOauthToken(java.lang.String oauthToken) {
      return (GetVictim) super.setOauthToken(oauthToken);
    }

    @Override
    public GetVictim setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetVictim) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetVictim setQuotaUser(java.lang.String quotaUser) {
      return (GetVictim) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetVictim setUserIp(java.lang.String userIp) {
      return (GetVictim) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetVictim setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetVictim set(String parameterName, Object value) {
      return (GetVictim) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertVictim".
   *
   * This request holds the parameters needed by the victimendpoint server.  After setting any
   * optional parameters, call the {@link InsertVictim#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link epusp.pcs.os.model.person.victimendpoint.model.Victim}
   * @return the request
   */
  public InsertVictim insertVictim(epusp.pcs.os.model.person.victimendpoint.model.Victim content) throws java.io.IOException {
    InsertVictim result = new InsertVictim(content);
    initialize(result);
    return result;
  }

  public class InsertVictim extends VictimendpointRequest<epusp.pcs.os.model.person.victimendpoint.model.Victim> {

    private static final String REST_PATH = "victim";

    /**
     * Create a request for the method "insertVictim".
     *
     * This request holds the parameters needed by the the victimendpoint server.  After setting any
     * optional parameters, call the {@link InsertVictim#execute()} method to invoke the remote
     * operation. <p> {@link
     * InsertVictim#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link epusp.pcs.os.model.person.victimendpoint.model.Victim}
     * @since 1.13
     */
    protected InsertVictim(epusp.pcs.os.model.person.victimendpoint.model.Victim content) {
      super(Victimendpoint.this, "POST", REST_PATH, content, epusp.pcs.os.model.person.victimendpoint.model.Victim.class);
    }

    @Override
    public InsertVictim setAlt(java.lang.String alt) {
      return (InsertVictim) super.setAlt(alt);
    }

    @Override
    public InsertVictim setFields(java.lang.String fields) {
      return (InsertVictim) super.setFields(fields);
    }

    @Override
    public InsertVictim setKey(java.lang.String key) {
      return (InsertVictim) super.setKey(key);
    }

    @Override
    public InsertVictim setOauthToken(java.lang.String oauthToken) {
      return (InsertVictim) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertVictim setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertVictim) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertVictim setQuotaUser(java.lang.String quotaUser) {
      return (InsertVictim) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertVictim setUserIp(java.lang.String userIp) {
      return (InsertVictim) super.setUserIp(userIp);
    }

    @Override
    public InsertVictim set(String parameterName, Object value) {
      return (InsertVictim) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listVictim".
   *
   * This request holds the parameters needed by the victimendpoint server.  After setting any
   * optional parameters, call the {@link ListVictim#execute()} method to invoke the remote operation.
   *
   * @return the request
   */
  public ListVictim listVictim() throws java.io.IOException {
    ListVictim result = new ListVictim();
    initialize(result);
    return result;
  }

  public class ListVictim extends VictimendpointRequest<epusp.pcs.os.model.person.victimendpoint.model.CollectionResponseVictim> {

    private static final String REST_PATH = "victim";

    /**
     * Create a request for the method "listVictim".
     *
     * This request holds the parameters needed by the the victimendpoint server.  After setting any
     * optional parameters, call the {@link ListVictim#execute()} method to invoke the remote
     * operation. <p> {@link
     * ListVictim#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListVictim() {
      super(Victimendpoint.this, "GET", REST_PATH, null, epusp.pcs.os.model.person.victimendpoint.model.CollectionResponseVictim.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListVictim setAlt(java.lang.String alt) {
      return (ListVictim) super.setAlt(alt);
    }

    @Override
    public ListVictim setFields(java.lang.String fields) {
      return (ListVictim) super.setFields(fields);
    }

    @Override
    public ListVictim setKey(java.lang.String key) {
      return (ListVictim) super.setKey(key);
    }

    @Override
    public ListVictim setOauthToken(java.lang.String oauthToken) {
      return (ListVictim) super.setOauthToken(oauthToken);
    }

    @Override
    public ListVictim setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListVictim) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListVictim setQuotaUser(java.lang.String quotaUser) {
      return (ListVictim) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListVictim setUserIp(java.lang.String userIp) {
      return (ListVictim) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListVictim setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListVictim setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListVictim set(String parameterName, Object value) {
      return (ListVictim) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeVictim".
   *
   * This request holds the parameters needed by the victimendpoint server.  After setting any
   * optional parameters, call the {@link RemoveVictim#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public RemoveVictim removeVictim(java.lang.Long id) throws java.io.IOException {
    RemoveVictim result = new RemoveVictim(id);
    initialize(result);
    return result;
  }

  public class RemoveVictim extends VictimendpointRequest<Void> {

    private static final String REST_PATH = "victim/{id}";

    /**
     * Create a request for the method "removeVictim".
     *
     * This request holds the parameters needed by the the victimendpoint server.  After setting any
     * optional parameters, call the {@link RemoveVictim#execute()} method to invoke the remote
     * operation. <p> {@link
     * RemoveVictim#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveVictim(java.lang.Long id) {
      super(Victimendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveVictim setAlt(java.lang.String alt) {
      return (RemoveVictim) super.setAlt(alt);
    }

    @Override
    public RemoveVictim setFields(java.lang.String fields) {
      return (RemoveVictim) super.setFields(fields);
    }

    @Override
    public RemoveVictim setKey(java.lang.String key) {
      return (RemoveVictim) super.setKey(key);
    }

    @Override
    public RemoveVictim setOauthToken(java.lang.String oauthToken) {
      return (RemoveVictim) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveVictim setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveVictim) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveVictim setQuotaUser(java.lang.String quotaUser) {
      return (RemoveVictim) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveVictim setUserIp(java.lang.String userIp) {
      return (RemoveVictim) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public RemoveVictim setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveVictim set(String parameterName, Object value) {
      return (RemoveVictim) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateVictim".
   *
   * This request holds the parameters needed by the victimendpoint server.  After setting any
   * optional parameters, call the {@link UpdateVictim#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link epusp.pcs.os.model.person.victimendpoint.model.Victim}
   * @return the request
   */
  public UpdateVictim updateVictim(epusp.pcs.os.model.person.victimendpoint.model.Victim content) throws java.io.IOException {
    UpdateVictim result = new UpdateVictim(content);
    initialize(result);
    return result;
  }

  public class UpdateVictim extends VictimendpointRequest<epusp.pcs.os.model.person.victimendpoint.model.Victim> {

    private static final String REST_PATH = "victim";

    /**
     * Create a request for the method "updateVictim".
     *
     * This request holds the parameters needed by the the victimendpoint server.  After setting any
     * optional parameters, call the {@link UpdateVictim#execute()} method to invoke the remote
     * operation. <p> {@link
     * UpdateVictim#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link epusp.pcs.os.model.person.victimendpoint.model.Victim}
     * @since 1.13
     */
    protected UpdateVictim(epusp.pcs.os.model.person.victimendpoint.model.Victim content) {
      super(Victimendpoint.this, "PUT", REST_PATH, content, epusp.pcs.os.model.person.victimendpoint.model.Victim.class);
    }

    @Override
    public UpdateVictim setAlt(java.lang.String alt) {
      return (UpdateVictim) super.setAlt(alt);
    }

    @Override
    public UpdateVictim setFields(java.lang.String fields) {
      return (UpdateVictim) super.setFields(fields);
    }

    @Override
    public UpdateVictim setKey(java.lang.String key) {
      return (UpdateVictim) super.setKey(key);
    }

    @Override
    public UpdateVictim setOauthToken(java.lang.String oauthToken) {
      return (UpdateVictim) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateVictim setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateVictim) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateVictim setQuotaUser(java.lang.String quotaUser) {
      return (UpdateVictim) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateVictim setUserIp(java.lang.String userIp) {
      return (UpdateVictim) super.setUserIp(userIp);
    }

    @Override
    public UpdateVictim set(String parameterName, Object value) {
      return (UpdateVictim) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Victimendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Victimendpoint}. */
    @Override
    public Victimendpoint build() {
      return new Victimendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link VictimendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setVictimendpointRequestInitializer(
        VictimendpointRequestInitializer victimendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(victimendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
